# Generated by Django 2.0.6 on 2018-07-03 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('lot_id', models.CharField(max_length=255, unique=True)),
                ('lot_name', models.CharField(default=None, max_length=255)),
                ('street_address', models.CharField(default=None, max_length=512, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingReservation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reservation_unique', models.CharField(default=None, max_length=16)),
                ('username', models.CharField(default=None, max_length=255)),
                ('time_start', models.DateTimeField(default=None)),
                ('time_expires', models.DateTimeField(default=None)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSpace',
            fields=[
                ('oid', models.UUIDField(default=None)),
                ('mac_address', models.CharField(default=None, max_length=255, primary_key=True, serialize=False)),
                ('parking_space_id', models.CharField(default=None, max_length=255, unique=True)),
                ('car_counter', models.IntegerField(null=True)),
                ('car_presence', models.IntegerField(default=0)),
                ('sensor_status', models.CharField(choices=[('Unknown', 'Unknown'), ('Vacant', 'Vacant'), ('Occupied', 'Occupied')], default='Unknown', max_length=255)),
                ('published', models.BooleanField(default=False)),
                ('available_from', models.TimeField(null=True)),
                ('available_to', models.TimeField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('parking_lot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ParkingLot')),
            ],
        ),
        migrations.AddField(
            model_name='parkingreservation',
            name='parking_space',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ParkingSpace'),
        ),
    ]
