# Generated by Django 2.0.6 on 2018-07-03 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingreservation',
            name='time_expires',
        ),
        migrations.RemoveField(
            model_name='parkingreservation',
            name='time_start',
        ),
    ]
