# Generated by Django 2.0.6 on 2018-07-03 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180703_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingreservation',
            name='datetime_expire',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='parkingreservation',
            name='datetime_start',
            field=models.DateTimeField(default=None),
        ),
    ]
