# Generated by Django 2.0.6 on 2018-07-03 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180703_0330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingreservation',
            name='datetime_expire',
        ),
        migrations.RemoveField(
            model_name='parkingreservation',
            name='datetime_start',
        ),
    ]
