# Generated by Django 2.0.6 on 2018-07-03 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180703_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingreservation',
            name='time_expire',
            field=models.TimeField(default=None),
        ),
        migrations.AddField(
            model_name='parkingreservation',
            name='time_start',
            field=models.TimeField(default=None),
        ),
    ]
