# Generated by Django 2.0.6 on 2018-07-03 02:11

import api.converters
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180703_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingreservation',
            name='reservation_unique',
            field=models.CharField(default=api.converters.conv.generate_unique_res, max_length=16),
        ),
    ]
