# Generated by Django 2.0.6 on 2018-07-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(default=None, max_length=1024)),
                ('user_id', models.CharField(default=None, max_length=255)),
                ('company_id', models.CharField(default=None, max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
