# Generated by Django 2.0.6 on 2018-07-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_email',
            field=models.CharField(default=None, max_length=512, unique=True),
        ),
    ]
